environment:
  matrix:
  -nodejs_version: "6"

install:
  #get lates stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  #install modules
  - npm install

# Post-install test scripts
test_script:
  #output usefull info for debugging
  -node --version
  -npm --version
  # run test_script
  - nom test

# Don't acctually build
build: off